### ISSUE TITLE
[Issue] Loading up crash

### ISSUE THREAD

**Issue by accessdenied0** [JackyyTV/Exchangers#10]
I got an issue, probably related to #8.

The [crashlog](https://pastebin.com/1XQx9zMp) is very similar. Only I using more mods and a newer Forge (14.21.1.2407 -> 14.21.1.2413) and Exchangers (Exchangers-1.12-2.1.2) version.

I got this issue soon I added "Unique Crops" to my modlist. But sadly this is not the only time I got this issue. It even sometimes happen randomly on startup.

access_denied

**Comment by JackyyTV** [comment]
What pack are you playing? A custom pack or modpacks on Curse?
It seems like I might have to convert some of these crafting recipes to the new system, since it's causing crashes with old shaped crafting.

**Comment by accessdenied0** [comment]
Custom. I strongly modified the All the Mods3 pack... So far I get the impression 1.12 is pretty bad... it messed up the whole crafting system.

**Comment by JackyyTV** [comment]
Ah I see. And yes, 1.12 modded's crafting system is messed up thanks to Forge registry rewrite, wasn't as bad before the rewrite though.
Sidenote: I am fixing this bug at the moment. Mind if I drop a jar file here when I finished doing that and test it for me before I push the update?

**Comment by accessdenied0** [comment]
Sure thing, I'm thankful for you help.

**Comment by JackyyTV** [comment]
There you go. Try this and let me know if it still does the occasional crashes.
https://www.dropbox.com/s/26xir0275roclm0/Exchangers-1.12-2.2.jar?dl=0

**Comment by accessdenied0** [comment]
Works perfectly fine! Thank you for your fast fix and this nice conversation!

**Comment by JackyyTV** [comment]
No problem. I'll now backport some fixes to 1.10.2 and 1.11.2, then push the releases onto CurseForge.
