### ISSUE TITLE
Can't disable Vanilla style Exchangers

### ISSUE THREAD

**Issue by JamesGrimm** [JackyyTV/Exchangers#11]
### Issue type (Crash / Bug report / Suggestion):
Config switch to disable Vanilla exchangers doesn't work.

### Crash report (If applicable, **put the crash report in pastebin, gist, etc.**):
No crash.

### Affected version (If applicable):
**Minecraft version**: 1.12
**Forge version**: Most recent (as of 7/16/2017)
**Exchangers version**: 1.12-2.2
--*Put the versions of other mods below this line if needed*--

### Issue Description:
Config file has an listing to disable modules. I want there to only be Thermal Expansion Exchangers, but when I set "B:Vanilla Module=False" the Vanilla exchangers still show up in JEI and are craftable.

### Steps to reproduce (If applicable):
Set config switch, start Minecraft, open JEI, search for "@exchange"

**Comment by JackyyTV** [comment]
Very weird, will have a look into it.

**Comment by JackyyTV** [comment]
Do the vanilla exchangers still got recipes even if disabled?

**Comment by TheTurkeyDev** [comment]
Just tested myself and everything is working just fine. make sure you are changing `B:"Vanilla Module"=false` and not `B:"Vanilla Progressive Recipes"=true` as the later only changes the recipes and doesn't actually remove them.

**Comment by JamesGrimm** [comment]
I just double checked this after your answer.

Can confirm from the Config, that I have both Vanilla switches set to false. For a test I set *every* module setting in the config to false except "B:"Thermal Expansion Module"=true" (so all of the Progressive switches), and loaded up.

Full set of Vanilla & Thermal Exchangers in JEI, and the recipes are all the same as with Progressive on.

So for some reason the config is not altering the in-game settings for me. Do not know why you can't reproduce.

**Comment by JackyyTV** [comment]
Hmm... I'll investigate that with Turkey. For now, reopening the issue.

**Comment by wjrogers** [comment]
I have the same problem on Exchangers-1.11.2-1.3. Vanilla exchanges are still available in-game with recipes Have attached my config file. "Progressive recipes" settings also don't seem to have any effect.
[exchangers.cfg.txt](https://github.com/Jacky1356400/Exchangers/files/1163005/exchangers.cfg.txt)

**Comment by JackyyTV** [comment]
I am kinda busy recently, will have a look rewriting the config part when I have time.

**Comment by wjrogers** [comment]
I see the problem: all your config checks when you register your items use `=` (assignment) where you mean `==` (comparison). Would be simpler to just leave off the `== true` entirely and use the value of the config property directly; e.g.
```
        if (Config.vanillaModule) {
            ...
        }
```

**Comment by JackyyTV** [comment]
That is actually changed in the 1.12 branch, I just haven't backported it to 1.10.2 and 1.11.2 yet, gonna see if that helps.

**Comment by JackyyTV** [comment]
Will be releasing a new version of Exchangers, which should disables the recipes of the Exchangers properly (the disabled items will be hidden for 1.10.2 and 1.11.2, and the disable items will just have their recipes disabled for 1.12, they'll still show up but should be uncraftable).

**Comment by JamesGrimm** [comment]
Just tested. Can confirm - Problem Fixed!

Only the TE Exchangers have craftable recipes. Thank you!
