### ISSUE TITLE
[Issue] Crash while playing

### ISSUE THREAD

**Issue by accessdenied0** [JackyyTV/Exchangers#12]
### Issue type (Crash / Bug report / Suggestion):
Issue: Crash

### Crash report (If applicable, **put the crash report in pastebin, gist, etc.**):
[Crash report](https://pastebin.com/ggjL1J1f)

### Game log (If applicable, **put the log in pastebin, gist, etc.**):
//It is very big I upload only if really necessary.

### Affected version (If applicable):
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2297
**Exchangers version**: 1.3
--*Put the versions of other mods below this line if needed*--
//Slight modified version of "Forever Stranded"

### Issue Description:
Crash randomly mid game after using Exchanger a few times. It didn't crashed while Exchanger was not crafted.

### Steps to reproduce (If applicable):
I _guess_ just download "Forever Stranded" or weather2 mod and use the Exchanger?!?

**Comment by JackyyTV** [comment]
Weather2 sand layer is causing the crash, will have to have a look into its source code and blacklist it.

**Comment by accessdenied0** [comment]
I thank you very much for you fast help and I'm sorry for the extra work.

**Comment by orionSquared** [comment]
I am having this same issue with Biomes o' Plenty things. I didn't try to use the exchanger on BoP blocks, but when I had it in my hand, and my curser moved over BoP grass (not the block, but the part that sticks out of the ground), it crashed me to desktop. Recreated twice.

**Comment by JackyyTV** [comment]
Yeah, the current exchanger mechanics only partially works as it's blacklisted based on vanilla blocks. On the next update for 1.10.2/1.11.2/1.12, the mechanics will be completely re-written as to be more compatible with modded blocks.
There will also be Forge Energy support, which means RF-based exchangers will be able to charge through FE-based tile entitles / items (e.g. Actually Additions Energizer, Tech Reborn power storage / batteries, etc.)

**Comment by orionSquared** [comment]
I promise I'm not wanting to rush you. Merely curious if there's an ETA on this update. I only ask because I'm trying to gauge if I want to wait to update my pack to include this mod or if I should go ahead and do an update and wait for the next one to add this mod.

I just really love the mod and I think it fits so well into my pack's play style.

**Comment by JackyyTV** [comment]
I am not sure yet. Currently @Turkey2349 is the one that does bug fixes for this mod, but he hasn't work on the rewrite yet. I've been rather busy with real life recently, so don't really have time to manage this project anymore. Plus, I've got plans for a couple of new mods to be released when I am not busy (hopefully).

**Comment by JackyyTV** [comment]
New Exchangers update coming soon (hopefully by tomorrow), I've rewritten the whole Exchanger mechanics, hopefully shouldn't cause more crashes.
**Edit**: Though it should be noted, you only get 1 sand layer back no matter how many layers are there in a block.
Here's a preview of the new mechanics:
https://gfycat.com/CleverRemarkableEwe

**Comment by orionSquared** [comment]
This is awesome. So hopefully no more conflict with BoP?

**Comment by JackyyTV** [comment]
Yes, shouldn't be causing any issues with BoP plants either.

**Comment by orionSquared** [comment]
You're literally the best. Super excited to have this mod again.

**Comment by accessdenied0** [comment]
Point. I can't add anything to that. Thank you @Jacky1356400 !
