### ISSUE TITLE
Minecraft 1.12 server crash

### ISSUE THREAD

**Issue by Realever** [JackyyTV/Exchangers#13]
Hi
I have a problem my server crash after i updatet to your newer version 2.3. Here is the crash report: https://pastebin.com/xLP7f3Ng .
My server is on 1.12 and i use forge version 2428

**Comment by JackyyTV** [comment]
Oops, my bad. Rewritten the exchangers overlay but forgot to move that into client proxy instead of common proxy, will release a fix ASAP.

**Comment by JackyyTV** [comment]
2.3.1 now available on [CurseForge](https://minecraft.curseforge.com/projects/exchangers/files/2458498).
