### ISSUE TITLE
1.11.2 Server Crash

### ISSUE THREAD

**Issue by laserlemons** [JackyyTV/Exchangers#14]
### Issue type (Crash / Bug report / Suggestion):
Crash

### Crash report (If applicable, **put the crash report in pastebin, gist, etc.**):
https://pastebin.com/S8uYXx91

### Affected version (If applicable):
**Minecraft version**: 1.11.2
**Forge version**: 2386
**Exchangers version**: 1.4.1
--*Put the versions of other mods below this line if needed*--

### Issue Description:
Server crash on startup

**Comment by laserlemons** [comment]
I lied! I was on 1.4.

**Comment by JackyyTV** [comment]
...
I had to double check the codes on my side then xD

**Comment by laserlemons** [comment]
The Twitch launcher had 1.4 labeled as the latest version at the time of posting. I didn't bother double-checking the version number until afterward.

**Comment by JackyyTV** [comment]
Yeah, it takes a while for the Twitch Desktop App to update, but yes, I've already fixed it after I saw #13.
