### ISSUE TITLE
Exchangers do not work with Chisel blocks

### ISSUE THREAD

**Issue by thundr** [JackyyTV/Exchangers#19]
### Issue type (Crash / Bug report / Suggestion):
Title

### Affected version (If applicable):
**Minecraft version**: 1.12
**Forge version**:  14.21.1.2428
**Exchangers version**:  Exchangers-1.12-2.2
--*Put the versions of other mods below this line if needed*--

### Issue Description:

Exchanger GUI shows 0 of the selected blocks in inventory, tested with multiple variants and types. 

### Steps to reproduce (If applicable):

Choose a chisel block, try to exchange.

**Comment by JackyyTV** [comment]
Have you tried reproducing this bug on [2.3.1](https://minecraft.curseforge.com/projects/exchangers/files/2458498)? 2.2 is rather outdated and I've rewritten the exchanger mechanics and removed the selected item in GUI.

**Comment by thundr** [comment]
I run it on a server, I'll get everyone on a new version next patch of the modpack. Will update the issue then.

**Comment by JackyyTV** [comment]
Alright, hopefully the issue should the fixed then.

**Comment by thundR** [comment]
I should also add, though that version is 3 weeks old, it is the version that all the mods 3 uses right now, unless they have updated without putting it in the patch notes, which I think is unlikely.

**Comment by JackyyTV** [comment]
I have All the Mods 3 v2.7 on my Twitch desktop app, not the latest (v2.8) but Exchangers is on the latest version (2.3.1).

**Comment by thundr** [comment]
Yea I deleted my comment, was spurious anyways

**Comment by JackyyTV** [comment]
Oh, I still saw that on my side, probably needed a refresh on the page.

**Comment by ThatGamerBlue** [comment]
Cannot confirm using latest exchangers and latest chisel using minecraft 1.12.

**Comment by ThatGamerBlue** [comment]
Actually I'm gonna leave this open for now, it's odd that it didn't work before.

@Jacky1356400 close if you want

**Comment by JackyyTV** [comment]
I'll leave it open for now, until I get a response.

**Comment by thundr** [comment]
Updating the mod seemed to fix the problem, I'm going to close this issue now. Thanks for the help, and thanks for the great mod.

**Comment by JackyyTV** [comment]
Alright, let me know again if it doesn't work.
