### ISSUE TITLE
[1.12] Mekanism Exchangers have no recipes

### ISSUE THREAD

**Issue by TheLimePixel** [JackyyTV/Exchangers#20]
### Affected version (If applicable):
**Minecraft version**: 1.12.1
**Forge version**: 14.22.0.2456
**Exchangers version**: 2.3.1
**Mekanism version**: 1.9.4.0.318

### Issue Description:
 As the title suggests, the Mekanism Exchangers don't have recipes.

**Comment by JackyyTV** [comment]
Is the Mekanism module enabled in config? I've re-added Mekanism integration back in 2.3, but old configs still has it disabled. You'll have to manually enable / delete the old config to get the recipes.

**Comment by JackyyTV** [comment]
Also, I assume that's in Modern Skyblock 2 (since you're the pack creator for it). I am actually in your Discord server (Discord tag: Jacky#3044). Feel free to poke me there if you found any issues regarding my mods.

**Comment by JackyyTV** [comment]
Just tested myself with the exact same Forge and mod versions, couldn't reproduce this bug, could well be you have the Mekanism module disabled in config.
