### ISSUE TITLE
Load time NPE related to getDisplayName() on stacks

### ISSUE THREAD

**Issue by asiekierka** [JackyyTV/Exchangers#21]
### Issue type (Crash / Bug report / Suggestion):

Crash

### Crash report (If applicable, **put the crash report in pastebin, gist, etc.**):

http://paste.asie.pl/NEqA

### Game log (If applicable, **put the log in pastebin, gist, etc.**):

N/A

### Affected version (If applicable):
**Minecraft version**: 1.12.1
**Forge version**: 14.22.0.2457
**Exchangers version**: 1.12-2.3.1
--*Put the versions of other mods below this line if needed*--

### Issue Description:

Crashes on game load

### Steps to reproduce (If applicable):

Seems to happen randomly

**Comment by JackyyTV** [comment]
Interesting crash... thanks for letting me know asie, will have a look into it.

**Comment by JackyyTV** [comment]
Think I've found the issue... Mode key in ExchangerHandler was called before `keys.init()` in ClientProxy. This seems to happen quite randomly. Hopefully the patch I am pushing should fix this.
