### ISSUE TITLE
Creosote Problem?

### ISSUE THREAD

**Issue by Rudy2D2** [JackyyTV/Exchangers#26]
### Affected version (If applicable):
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2488
**Exchangers version**: 1.10.2-1.5
--*Put the versions of other mods below this line if needed*--
Latest version of all mods used.
### Issue Description:
Creosote oil from Immersive Engineering/Railcraft breaks (no texture, can't be collected/used in a bucket).

### Steps to reproduce (If applicable):
I cannot reproduce with just Echangers, IE and RC installed. I have a LOT of other mods installed, so I don't have time to try out every combination, but when I remove this mod I don't have the problem. I was wondering if you could think of any reason why this would be happening.

**Comment by JackyyTV** [comment]
Duplicate of #6, which is a known bug and has been mentioned in CoFH/Feedback#366.

**Comment by JackyyTV** [comment]
Unfortunately, I can't do much about that, since the author of Immersive Engineering decided not to maintain the 1.10.2 version anymore.
