### ISSUE TITLE
Incompatible with Tinkers Construct Seared Blocks of any kind.

### ISSUE THREAD

**Issue by Dragnier** [JackyyTV/Exchangers#27]
### Issue type (Crash / Bug report / Suggestion):

Bug Report and Suggestion

### Crash report (If applicable, **put the crash report in pastebin, gist, etc.**):

N/A

### Game log (If applicable, **put the log in pastebin, gist, etc.**):

N/A

### Affected version (If applicable):

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2512
**Exchangers version**: 1.12-2.4

--*Put the versions of other mods below this line if needed*--

**Tinkers Construct version**: 1.12-2.7.3.30

### Issue Description:

**Bug**

Exchangers do not see Seared Stone items from Tinkers Construct as a valid block. Tried to set Seared Paver as the selected block by sneak-right-click and it said invalid block. I wanted to use the Leadstone Exchanger to make my floor. These blocks are all the same block id with different meta data. I was able to select Clear Glass from Tinkers Construct as a valid block though, so I don't know what the issue is.

**Suggestion**

You may also want to consider adding a way to simply clear the selected block rather than it always remembering the last block selected. Perhaps a keybind or even better sneak-right-click the air.

### Steps to reproduce (If applicable):

1. Make any Seared Stone block; I was using Seared Paver.
2. Try to set it as the selected block with an exchanger; I used the Leadstone Exchanger.
3. Chat says the block is invalid.

**Comment by JackyyTV** [comment]
Exchangers blacklists all of the tile entitles as it can cause a few issues, or even world corruption.
That is currently hard-coded into the mod, but I can make a config option at some point, so that tile entities are exchangable.

**Comment by Dragnier** [comment]
They are not Tile Entities. They are just blocks with meta data (damage values) to specify which texture gets used. Tile Entities are things like Hoppers, Droppers, and modded machines such as the Pulverizer from Thermal Expansion. Seared Stone blocks are no different from how the Clear Glass works.

**Comment by JackyyTV** [comment]
Actually no from what I've found in TCon's source codes, apparently those smeltery blocks creates a tile entity upon placed. I'll see what I can do about it, maybe end up adding a whitelist for TCon smeltery blocks.
https://github.com/SlimeKnights/TinkersConstruct/blob/7e3630e443aed150f95c662ba6ca78976cb31bed/src/main/java/slimeknights/tconstruct/smeltery/block/BlockEnumSmeltery.java#L41-L45

**Comment by Dragnier** [comment]
Ah, I didn't realize they handled it that way. Must have something to do with the Smeltery Controller being able to find out if it has valid blocks to create the Smeltery Multiblock.

**Comment by JackyyTV** [comment]
Yeah, I am hoping to sort that out when I have time as I've got 9+ projects on my hand at the moment.

**Comment by JackyyTV** [comment]
Fixed in [2.5](https://github.com/Jacky1356400/Exchangers/releases/tag/1.12-2.5).
This version is not on CurseForge yet, but I will be uploading it tonight.
