### ISSUE TITLE
Adding Forge Energy support

### ISSUE THREAD

**Issue by JackyyTV** [JackyyTV/Exchangers#3]
I know I should have used Forge Energy instead of RF, but because I am not sure how to implement Forge Energy, it is not in the mod yet.
Because of [this](https://www.reddit.com/r/feedthebeast/comments/6j43mj/new_rewrite_update_for_exchangers_now_with/djbhh4b/), ~~I am switching over to FE completely~~.
Feel free to pull request my repo for adding FE.

**Comment by KingLemming** [comment]
You're actually good now on that for 1.10.2 (looking at your current repo), and I'm sorry - that was 100% on us and the API repo was just wrong.

For 1.12, the RF-API will be a 100% standalone jar. For an idea of how I set up Forge Energy support (it's *trivial* alongside RF), have a look here:

https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/capabilities/EnergyContainerItemWrapper.java

Implemented here in the Cell:

https://github.com/CoFH/ThermalExpansion/blob/master/src/main/java/cofh/thermalexpansion/block/storage/ItemBlockCell.java

**Comment by JackyyTV** [comment]
I am probably gonna keep RF support but adding FE at the same time for 1.10.2 and 1.11.2.
As for 1.12, Energy-based exchangers are not implemented yet so I will see when the supported mods are getting released.
