### ISSUE TITLE
Allow bigger energy capacity for exchangers

### ISSUE THREAD

**Issue by OneEyeMaker** [JackyyTV/Exchangers#31]
Hello.
Mostly, title says it all. For some modpacks energy storage cap at 100.000.000 RF (which specified [in configuration](https://github.com/Jacky1356400/Exchangers/blob/dev-1.12/src/main/java/me/jacky1356400/exchangers/Config.java#L190-L272)) is not enough.
Suggest to change this value to 1.000.000.000 of even ```Integer.MAX_VALUE```.
Also, you can also use this constant [here](https://github.com/Jacky1356400/Exchangers/blob/dev-1.12/src/main/java/me/jacky1356400/exchangers/Config.java#L173-L188) (instead of hardcoded value).

P. S. Thank you for your work!

**Comment by JackyyTV** [comment]
Good call. I shall change all of the energy values to allow `Integer.MAX_VALUE` instead.
