### ISSUE TITLE
Add Holding and Unbreaking enchant support for powered exchangers

### ISSUE THREAD

**Issue by Xiaminou** [JackyyTV/Exchangers#37]
Items from CoFH's mods can be enchanted with Holding to store more power (among other things) I think it would be nice to have Exchangers follow the game principle.

**Comment by JackyyTV** [comment]
Just a note, I've added Holding Enchant support in the latest version of Exchangers. However, due to unknown reasons, it does not work properly on 1.12 yet, but it does work on 1.10 and 1.11. I'll keep this issue open until I can get it to work on 1.12.

**Comment by Xiaminou** [comment]
I just read that CoFH also adds the Unbreaking enchant for powered items, apparently it's been changed to have a chance to reduce the power cost. Would be nice to have that too for Exchangers.

**Comment by JackyyTV** [comment]
2.6.1 (for 1.12) / 1.7.1 (for 1.10 / 1.11) are now available on CurseForge, which adds support for Unbreaking enchant, works on all MC versions. I still have no idea why Holding isn't working as intended on 1.12, so I'll keep this issue open until that resolved.

**Comment by Xiaminou** [comment]
Have you asked KingLemming? he might be able to help.

**Comment by JackyyTV** [comment]
Probably actually, I can ping him on Discord and see if he can help me.

**Comment by JackyyTV** [comment]
Finally found the problem, it was something to do with 1.12 Forge registry rewrite screwing up how objects are being fetched, so it tried to grab a null object with the 1.10 / 1.11 codes, hence why it didn't work.
I will push out a new update in probably a week since I've just pushed a new one today and this is really minor for now.

**Comment by JackyyTV** [comment]
Finally sorted this out in [2.6.2](https://minecraft.curseforge.com/projects/exchangers/files/2519378)!
