### ISSUE TITLE
Unable to exchange Blockcraftery blocks

### ISSUE THREAD

**Issue by Dragnier** [JackyyTV/Exchangers#38]
Issue type (Crash / Bug report / Suggestion):

Bug Report

Crash report (If applicable, put the crash report in pastebin, gist, etc.):

N/A

Game log (If applicable, put the log in pastebin, gist, etc.):

N/A

Affected version (If applicable):

Minecraft version: 1.12.2
Forge version: 14.23.1.2566
Exchangers version: 1.12-2.5.2

--Put the versions of other mods below this line if needed--

Blockcraftery version: 0.1.3

Issue Description:

Bug

Exchangers do not see Blockcraftery items as a valid block. Similar to previous issue #27 with Seared blocks from Tinkers.

Steps to reproduce (If applicable):

    Make any Blockcraftery block.
    Try to set it as the selected block with an exchanger.
    Chat says the block is invalid.

**Comment by JackyyTV** [comment]
This is not a bug, Blockcraftery blocks are tile entities, which means they are blocks stored with data. Exchanging tile entities will end up causing data loss in Exchanged blocks, or even, crash / world corruption. What I'll do is I'll implement an user-defined block whitelist for people to whitelist their own blocks if they really want to bypass the tile entity blacklist.
