### ISSUE TITLE
1.12.2 issue

### ISSUE THREAD

**Issue by RayzoRayy** [JackyyTV/Exchangers#42]
When I use this it works fine with swapping blocks and placing.... however it doesn't seem to work well with Chisel for me, sometimes it works, but most of the time it says Erroe block not found even though I have it in my inventory. Am I missing something, or this a bug with this mod or chisel?

**Comment by JackyyTV** [comment]
I know exactly what's wrong, will fix that in the next update.

**Comment by RayzoRayy** [comment]
Awesome ty :)

**Comment by JackyyTV** [comment]
Fixed in [2.6.1](https://minecraft.curseforge.com/projects/exchangers/files/2517321).
