### ISSUE TITLE
[2.6.1] Immersive Engineering Exchangers Tier 2 Exchanger Hard Recipe requires T3 cores

### ISSUE THREAD

**Issue by rgtexa** [JackyyTV/Exchangers#43]
Not sure if this is intended, but the hard recipes for the IE Exchangers seem a bit unbalanced for the MV Exchanger.

The LV Exchanger requires 2 Tier 1 cores, The HV Exchanger requires 2 Tier 3 cores. But the MV Exchanger also requires 2 Tier 3 cores, while I believe it should be 2 Tier 2 Cores.

**Comment by JackyyTV** [comment]
I know what's wrong, when I did a rewrite for 1.12 Exchangers, I might have accidentally screwed up a few things in the recipes, easy fix though.

**Comment by JackyyTV** [comment]
Fixed in [2.6.2](https://minecraft.curseforge.com/projects/exchangers/files/2519378).
