### ISSUE TITLE
[1.12.2] Rendering Issue w/ Light Level Overlay Reloaded

### ISSUE THREAD

**Issue by SnowShock35** [JackyyTV/Exchangers#44]
#### Issue Information

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2585
- Exchangers 1.12.2-2.6.1
- Other Mods:
  - Light Level Overlay Reloaded 1.1.4-mc1.12

#### Issue Description

When hovering over a block while the light level overlay is enabled (done by pressing `F4` - default hotkey) with an exchanger in hand causes a weird rendering issue allowing the player to see air pockets (caves, mine shafts, etc.).

My hypothesis is that both mods rendering something on the block causes issues.

#### Issue Media

![](https://ss.blamesnow.co.uk/2018/01/1515599740-3dd85dfa.png)

**Comment by SnowShock35** [comment]
Reported to oldjunyi/LightLevelOverlayReloaded/issues/13.

**Comment by JackyyTV** [comment]
That's some OpenGL issues that I still can't figure out, will try and fix it if possible though.

**Comment by SnowShock35** [comment]
@Turkey2349 did it not fix the issue?

**Comment by JackyyTV** [comment]
Don't worry, I've fixed the issue. New build will be pushed shortly.

**Comment by SnowShock35** [comment]
Okay, that's awesome thank you :smile:

**Comment by SnowShock35** [comment]
Just working on a dw20 pack update so the sooner the better, but no rush 🙂

**Comment by JackyyTV** [comment]
I am hoping the new version will be out in a few hours, but that depends how long it takes CurseForge to approve the files.

**Comment by JackyyTV** [comment]
Fixed in [2.6.2](https://minecraft.curseforge.com/projects/exchangers/files/2519378), you can have that for the DW20 update @SnowShock35. :)

**Comment by SnowShock35** [comment]
Thank you Jacky.
