### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Moobien** [JackyyTV/Exchangers#46]
Hey guys, loving the mod! I have 2 suggestions for features.

I am using the Dank/Null mod also and quite understandably blocks that go directly to inventory dont end up in the dank so my 2 suggestions are.

1) make it so exchanged blocks can go into the dank/null if they have slots for them.
2) if suggestion 1 is unfeasable have a config option that drops the replaced blocks in place so they can be 'picked up' vanilla style (they will then go into the dank/null

**Comment by JackyyTV** [comment]
I've implemented a Force Drop Items mode for your second suggestion, that should hopefully help you.
New version coming out soon.

**Comment by Moobien** [comment]
Thank you :)

**Comment by JackyyTV** [comment]
Added in [2.7](https://minecraft.curseforge.com/projects/exchangers/files/2532994), enjoy!

**Comment by CTH999** [comment]
Works great with [This One](https://github.com/p455w0rd/DankNull/issues/80)
(Already Implemented!)
