### ISSUE TITLE
Option for Harvest Level

### ISSUE THREAD

**Issue by nmarshall23** [JackyyTV/Exchangers#47]
I would like to set first 2 tiers of exchangers to not be able to pick up Obsidian. 

Game play this would have them make an error sound. So that player is hinted that can't cheeze the tool progression. Maybe the Harvest Level should also be on the tool tip.

**Comment by JackyyTV** [comment]
Added in [2.7.1](https://minecraft.curseforge.com/projects/exchangers/files/2537408), let me know if the feature needs to be further expanded!

**Comment by NielsPilgaard** [comment]
Would it be possible to increase the max mining level to ~15? 
I have custom mining levels up to 14, and it'd be nice to be able to use the Exchangers more.
Reference: https://github.com/NillerMedDild/Enigmatica2Expert/issues/46

**Comment by JackyyTV** [comment]
Open a new issue for that so I remember to add it on the next update.

**Comment by NielsPilgaard** [comment]
Will do, thanks.
