### ISSUE TITLE
Torch duplication bug

### ISSUE THREAD

**Issue by PrincedelaLune** [JackyyTV/Exchangers#49]
If you choose to place torches with the exchanger, the torches are not placed but instantly drop (don't replace the block) and no torches are consumed in your inventory. It hapened to me with the obsidian exchanger, don't know if the bug is for all exchangers ...

**Comment by JackyyTV** [comment]
That's weird, will have a look into that when I can.

**Comment by PrincedelaLune** [comment]
Okey, good luck !

**Comment by JackyyTV** [comment]
Should be fixed in [2.7.2](https://minecraft.curseforge.com/projects/exchangers/files/2558022), let me know if it's not working!
