### ISSUE TITLE
Please update all file references to Exchangers.cfg

### ISSUE THREAD

**Issue by Sakata-MC** [JackyyTV/Exchangers#51]
In linux, the case matters, so windows/linux installs can't be migrated without touching the filename. Please update file references to match in all instances.
Thanks for the hard work.

**Comment by JackyyTV** [comment]
On newer versions of the mod, the mod has switched to use the correctly cased file (`Exchangers.cfg`), so the lowercase one is no longer being used, just delete it as it won't affect anything at all. Thank you.
