### ISSUE TITLE
EIO exchangers wont charge

### ISSUE THREAD

**Issue by red360** [JackyyTV/Exchangers#53]
EIO exchangers wont except charge in EIO weird or wireless charger charge.  Exchanger ver 1.12.2-2.7.2.

**Comment by JackyyTV** [comment]
I am not able to reproduce the bug using these mods:
![image](https://user-images.githubusercontent.com/11830494/39910397-b50eab6e-5529-11e8-9d2a-0dbc2c992810.png)
Do you have [Redstone Flux](https://minecraft.curseforge.com/projects/redstone-flux) installed? That is required if you want to use any powered Exchangers, it's stated in the mod's description.
![image](https://user-images.githubusercontent.com/11830494/39910456-05987240-552a-11e8-8a40-e3784ba89bda.png)

**Comment by red360** [comment]
That was it. I install Redstone Flux and it works now.
Thanks.
