### ISSUE TITLE
[1.12.2] EnderIO darksteel exchanger recipe for easy mode crash on startup

### ISSUE THREAD

**Issue by AlexanderLaptev** [JackyyTV/Exchangers#55]
Crashlog (Pastebin): https://pastebin.com/ieg5ihVL
Minecraft version: _1.12.2_
Forge version: _14.23.4.2738_
Exchangers version: _2.7.3_

That happened when I switched to easy recipes mode. It seems like you haven't specified the key "O" for the easy EnderIO Darksteel exchanger recipe.
The mod is cool, keep working on it!

**Comment by JackyyTV** [comment]
Will be fixed on 2.8, recipes are being rewritten for 1.12 EIO as well.

**Comment by AlexanderLaptev** [comment]
OK, I'll be waiting for it. Thanks for help!

**Comment by JackyyTV** [comment]
Keeping the issue opened until it's fixed, so I can keep track on things.

**Comment by AlexanderLaptev** [comment]
OK

**Comment by JackyyTV** [comment]
Sorry for the delay on the update as I've been extremely busy, but this is finally fixed in [2.8](https://minecraft.curseforge.com/projects/exchangers/files/2621277)!
