### ISSUE TITLE
Exchangers incorrectly place blocks out of Staff of Power junk filter and ignore other item sources

### ISSUE THREAD

**Issue by asteranx** [JackyyTV/Exchangers#58]
## Base information
* Minecraft version: 1.12
* Mod version:
    Draconic Evolution: 1.12.2-2.3.17.321
    Exchangers: 1.12.2-2.8
* Minecraft Forge version:14.23.5.2768
* Mod Pack: FTB Revelation 2.6.0

## Repro Steps
With any Exchanger (EX) and Staff of Power (SoP) in inventory:
  1) Pick a block, designate it with the EX by shift right clicking on it in the world.
  2) Add that block to the junk filter of the SoP.
  3) Find a different block in the world and right click with the EX.
Result: The EX will consume the block stack out of the junk filter to do the exchange.

## Summary
I noticed this while playing with a /dank/null (DN) in my inventory; The EX was happy sourcing blocks from it until I got a SoP at which point it stopped working. I initially thought that this was an issue with the SoP, but the Better Builders' Wand (BBW) I was also using correctly ignores the SoP's junk filter.

A similar issue occurs with two DNs as well - the EX will source items from the first if it can (irrespective of settings on the DN preventing it from extracting the last stack/block), but ignore the second. Again, the BBW operates correctly, pulling as many blocks as it is allowed from the first DN and the remainder from the second.

**Comment by JackyyTV** [comment]
This is most likely due to Draconic Evolution implemented an item container interface on their Staff of Power, which Exchangers tries to search for item containers that implements that interface to consume blocks from them (e.g. /dank/null). I'll need to have a look and see how I can implement a fix for this when I have time.
(Apologies for the late reply, I am extremely busy with work and I've got loads of stuff going on in real life.)

**Comment by JackyyTV** [comment]
I have an unreleased build that has most likely solved the issue, I've tested it on my side and it worked fine, can you try it out and let me know if it works or not?
Download: [Click Here](http://jackyy.hk/stuff/minecraft/jars/Exchangers-1.12.2-2.9.jar)
You'll also need a new library mod called GunpowderLib for this build: [Click Here](https://www.curseforge.com/minecraft/mc-mods/gunpowderlib/files/2852431)

**Comment by JackyyTV** [comment]
Should be fixed in [2.9](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/2903998).
