### ISSUE TITLE
Mod Interop: IE Creosote Oil broken when Exchanger and Thermal Expansion installed

### ISSUE THREAD

**Issue by tommyTT** [JackyyTV/Exchangers#6]
**Issue Description:**
Some weird interoperability issue happens when I have Immersive Engineering, Thermal Expansion and Exchanger installed.

**What happens:**
Creosote Oil is registered, but doesn't have the IE texture (it's green now) and the usage is completely broken. The Coke Oven from IE won't produce it any more and it is not possible to fill a bucket.

**What you expected to happen:**
Creosote Oil behaves exactly the same no matter if Exchanger is installed or not.

**Steps to reproduce:**
1. Create completely new instance and install IE and TE (see versions below).
2. Start game and look up Creosote Oil. It shows the normal IE texture and with JEI you can see it being produced by the coke oven.
3. Stop the game and install Exchanger.
4. Start again and look up Creosote Oil again. It now has a green texture and a lot of stuff is broken.
5. Stop the game and remove Exchanger again.
6. After another start everything works again.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2345
Mods:
- CodeChickenLib-1.11.2-2.7.0.268-universal
- CoFHCore-1.11.2-4.2.3.8-universal
- Exchangers-1.11.2-1.1
- ImmersiveEngineering-0.11-62
- jei_1.11.2-4.5.0.290
- ThermalExpansion-1.11.2-5.2.3.6-universal
- ThermalFoundation-1.11.2-2.2.3.5-universal

**Your most recent log file where the issue was present:**
[Latest Log](https://gist.github.com/tommyTT/3dbd2e344ddd4914284fd295b7bdfa7a)

**Comment by JackyyTV** [comment]
Have you tested this on 1.10.2 as well?

**Comment by JackyyTV** [comment]
Also, I've found the issue. It's something to do with the conflicts between Thermal Foundation and Immersive Engineering as they both registered a creosote oil fluid and using the same fluid ID. There's nothing I can really do about it. You'll have to either submit an issue ticket to TE or IE about the fluid conflicts. Sorry!

**Comment by tommyTT** [comment]
Thanks for looking into it. I haven't tested in 1.10.2, but since this only happens when Exchanger is installed I thought I post this here first. Without this mod the conflict doesn't seem to be a problem, so I hoped something works differently on this side when it is installed. Might be a load order issue, but since TE is involved, it could be anything really ... unfortunately the easiest solution for now is to not use Exchanger, good work though!

**Comment by JackyyTV** [comment]
It is most likely TF, since the 1.10+ update actually added a lot of items that are originally from other mods (e.g. Constantan, Steel, Creosote oil, Plates, etc.), which actually causes conflicts with other mods that's already got the same thing before TF did and weird things happens.

**Comment by JackyyTV** [comment]
Just noticed [this](https://github.com/CoFH/Feedback/issues/366), thought I'd leave this here as a reference.
