### ISSUE TITLE
Allow Exchangers to pull blocks from a Dank Null

### ISSUE THREAD

**Issue by dagantang** [JackyyTV/Exchangers#62]

**Comment by JackyyTV** [comment]
This was already added since 2.7, unless you're using an outdated version of the mod, the chances are, you can already do that.

**Comment by dagantang** [comment]
i dont know how but its doesnt work.

**Comment by JackyyTV** [comment]
What version of Exchangers and /dank/null are you using?

**Comment by dagantang** [comment]
DankNull-1.12.2-1.7.89 Exchangers-1.12.2-2.8.jar
