### ISSUE TITLE
Charging Problems

### ISSUE THREAD

**Issue by Zure13** [JackyyTV/Exchangers#65]
Hello Guys,
I can not charge the Ender IO exchangers in the Ender IO chargers.
Any ideas or tips?

I'm running on 1.12.2
Forge 14.23.5.2854
Ender IO 5.2.61
EnderCore 0.5.76
Exchangers 2.9

**Comment by JackyyTV** [comment]
Do you have [Redstone Flux](https://www.curseforge.com/minecraft/mc-mods/redstone-flux) installed? It is a required dependency for this mod if you want to use power-based Exchangers.

**Comment by Zure13** [comment]
Yay, that fixed it! 
Thx a lot.
