### ISSUE TITLE
[1.12.2] Exchangers Endergy Issue

### ISSUE THREAD

**Issue by accessdenied0** [JackyyTV/Exchangers#66]
I found this issue which looks pretty similar to mine:  https://github.com/JackyyTV/Exchangers/issues/45

But I get a crash and recipe issue if [Endergy](https://www.curseforge.com/minecraft/mc-mods/ender-io-endergy) is installed, because of the Melodic Ingot (ingotMelodicAlloy).

I'm sorry if this was submitted already or if this issue has nothing to do with your mod.

[My Crash-Report](https://pastebin.com/CS4nt7Hr)

**Comment by JackyyTV** [comment]
That's weird, the game is trying to add the recipe for Melodic Exchanger but it can't find the telepad block from Ender IO, which crashed the game because the block passed as a null object in the recipe. Do you happen to have the telepad block disabled in your modpack?

**Comment by JackyyTV** [comment]
Should be fixed in [2.10](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/3174939) as I've changed the recipe for Melodic Exchanger.

**Comment by accessdenied0** [comment]
Thank you alot ^^
