### ISSUE TITLE
playing on a server, crashing when holding mekanism mk1 exanger

### ISSUE THREAD

**Issue by erikLundstedt** [JackyyTV/Exchangers#67]
clientOS: linux
serverOS: Windows 10

GunpowderLib-1.12.2-1.1.jar
Exchangers-1.12.2-2.9.jar

Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
MekanismTools-1.12.2-9.8.3.390

https://paste.ee/p/fjqK2

**Comment by JackyyTV** [comment]
Please rollback GunpowerLib to 1.0 in order to use the old version of Exchangers for now.

I am aware of this issue as I am working on a new update for Exchangers that'll be out soon, which requires GunpowderLib 1.1 as it adds support for Forge Energy.

**Comment by JackyyTV** [comment]
Fixed in [2.10](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/3174939).
