### ISSUE TITLE
Crash with 1.12 Forge-14.21.1.2397

### ISSUE THREAD

**Issue by ImAK9** [JackyyTV/Exchangers#8]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  AstralCore (astralsorcery-1.5.8.jar)
  AppleCore (AppleCore-mc1.12-2.2.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  Default Options (DefaultOptions_1.12-9.2.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.3-1.12-anarchy.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.1.1.2.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 7/6/17 4:50 PM
Description: Initializing game

java.lang.RuntimeException: Invalid shaped ore recipe: LSL, LCL, LFL, L, ingotLead, S, null, F, null, C, me.jacky1356400.exchangers.item.ItemBasic@5c2959f1, 
	at net.minecraftforge.common.crafting.CraftingHelper.parseShaped(CraftingHelper.java:338)
	at me.jacky1356400.exchangers.util.RecipeHelper.addOldShaped(RecipeHelper.java:54)
	at me.jacky1356400.exchangers.util.RecipeHelper.addOldShaped(RecipeHelper.java:93)
	at me.jacky1356400.exchangers.init.ModRegistry.initRecipes(ModRegistry.java:99)
	at me.jacky1356400.exchangers.init.ModRegistry.onRecipeRegistry(ModRegistry.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_567_ModRegistry_onRecipeRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:724)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:697)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.common.crafting.CraftingHelper.parseShaped(CraftingHelper.java:338)
	at me.jacky1356400.exchangers.util.RecipeHelper.addOldShaped(RecipeHelper.java:54)
	at me.jacky1356400.exchangers.util.RecipeHelper.addOldShaped(RecipeHelper.java:93)
	at me.jacky1356400.exchangers.init.ModRegistry.initRecipes(ModRegistry.java:99)
	at me.jacky1356400.exchangers.init.ModRegistry.onRecipeRegistry(ModRegistry.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_567_ModRegistry_onRecipeRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:724)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:697)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1070690680 bytes (1021 MB) / 2686976000 bytes (2562 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2397 160 mods loaded, 160 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2397.jar) 
	UCH	forge{14.21.1.2397} [Minecraft Forge] (forge-1.12-14.21.1.2397.jar) 
	UCH	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	securitycraft{v1.8.2.2} [SecurityCraft] ([1.12] SecurityCraft v1.8.2.2.jar) 
	UCH	adventurebags{0.6} [Adventure Bags] (ab-1.12-0.6r.jar) 
	UCH	actuallyadditions{1.12-r113} [Actually Additions] (ActuallyAdditions-1.12-r113.jar) 
	UCH	applecore{2.2.1} [AppleCore] (AppleCore-mc1.12-2.2.1.jar) 
	UCH	jei{4.7.1.71} [Just Enough Items] (jei_1.12-4.7.1.71.jar) 
	UCH	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCH	thedragonlib{1.12-4.0.1} [TheDragonLib] (thedragonlib-1.12-4.0.1.jar) 
	UCH	armorplus{1.12-11.3.0.7-alpha} [ArmorPlus] (armorplus-1.12-11.3.0.7-alpha.jar) 
	UCH	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCH	astralsorcery{1.5.8} [Astral Sorcery] (astralsorcery-1.5.8.jar) 
	UCH	attaineddrops2{3.3.0} [Attained Drops 2] (Attained Drops-1.12-3.3.0.jar) 
	UCH	babyanimals{1.11-2} [Baby Animals Model Swapper] (BabyAnimals-1.11-2.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCH	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2288} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2288-universal.jar) 
	UCH	blockdrops{1.3.0} [Block Drops] (blockdrops-1.12-1.3.0.jar) 
	UCH	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.12-1.5.1.jar) 
	UCH	blur{1.0.3-13} [Blur] (Blur-1.0.3-13.jar) 
	UCH	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCH	ceramics{1.12-1.3.1} [Ceramics] (Ceramics-1.12-1.3.1.jar) 
	UCH	chameleon{1.12-4.1.0} [Chameleon] (Chameleon-1.12-4.1.0.jar) 
	UCH	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UCH	claybucket{1.0} [Clay Bucket] (ClayBucket-1.12-1.0.jar) 
	UCH	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCE	redstoneflux{2.0.0} [Redstone Flux] (RedstoneFlux-1.12-2.0.0.1-universal.jar) 
	UCE	cofhcore{4.3.0} [CoFH Core] (CoFHCore-1.12-4.3.0.5-universal.jar) 
	UCH	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.5-universal.jar) 
	UCH	controlling{3.0.1} [Controlling] (Controlling-3.0.1.jar) 
	UCH	cosmeticarmorreworked{1.12-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.12-v1.jar) 
	UCH	craftingtweaks{8.1.1} [Crafting Tweaks] (CraftingTweaks_1.12-8.1.1.jar) 
	UCH	ctm{MC1.12-0.1.1.2} [CTM] (CTM-MC1.12-0.1.1.2.jar) 
	UCH	custombackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-MC1.12-1.1.1.jar) 
	UCH	custommainmenu{2.0.6} [Custom Main Menu] (CustomMainMenu-MC1.12-2.0.6.jar) 
	UCH	cyclicmagic{1.5.9} [Cyclic] (Cyclic-1.12-1.5.9.jar) 
	UCH	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCH	darkutils{1.6.159} [Dark Utilities] (DarkUtils-1.12-1.6.159.jar) 
	UCH	ic2{2.8.4-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.4-ex112.jar) 
	UCH	forestry{5.4.3.128} [Forestry] (forestry_1.12-5.4.3.128.jar) 
	UCH	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UCH	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.12-1.4.8beta1.jar) 
	UCH	defaultoptions{9.2.1} [Default Options] (DefaultOptions_1.12-9.2.1.jar) 
	UCH	doggytalents{v1.13.1g} [Doggy Talents] (DoggyTalents-1.12-v1.13.1g-universal.jar) 
	UCH	durabilityshow{5.0.0} [Durability Show] (Durability Show-1.12-5.0.0.jar) 
	UCH	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	UCH	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCH	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.12-14.21.1.2387.jar) 
	UCH	embers{0.219} [Embers] (embers-0.219.jar) 
	UCH	csb_ench_table{1.1.2-beta2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2-beta2.jar) 
	UCH	endercompass{1.2.6} [Ender Compass] (EnderCompass-1.12-1.2.6.jar) 
	UCH	endercrop{1.12-1.3.4} [Ender Crop] (endercrop-1.12-1.3.4.jar) 
	UCH	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCH	endertanks{1.6.0.1} [EnderTanks] (endertanks-1.12.0-1.6.0.1.jar) 
	UCH	enderutilities{0.7.1} [Ender Utilities] (enderutilities-1.12.0-0.7.1.jar) 
	UCE	thermalfoundation{2.3.0} [Thermal Foundation] (ThermalFoundation-1.12-2.3.0.3-universal.jar) 
	UCE	thermalexpansion{5.3.0} [Thermal Expansion] (ThermalExpansion-1.12-5.3.0.4-universal.jar) 
	UCH	exchangers{1.12-2.1} [Exchangers] (Exchangers-1.12-2.1.jar) 
	UCH	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCH	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCH	fastfood{0.2.20848635} [Fast Food] (FastFood-0.2.20848635.jar) 
	UCH	flatbedrockx{1.4.0} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.4.0_1.12.jar) 
	UCH	flatcoloredblocks{mc1.12-6.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.2.jar) 
	UCH	floricraft{beta-4.2.0} [Floricraft] (Floricraft-1.12-beta4.2.0.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.3-1.12-anarchy.jar) 
	UCH	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCH	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.12-alpha-0.0.1.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	guideapi{1.12-2.1.3-55} [Guide-API] (Guide-API-1.12-2.1.3-55.jar) 
	UCH	immcraft{1.3.3} [Immersive Craft] (immcraft-1.12-1.3.3.jar) 
	UCH	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.12.jar) 
	UCH	inventorytweaks{1.63+dev.98.684f99a} [Inventory Tweaks] (InventoryTweaks-1.63+dev.98.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCH	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCH	itlt{1.0.0} [It's the little things] (itlt-1.12-1.0.0.jar) 
	UCH	itorch{1.1.7} [iTorch] (itorch-1.1.7.jar) 
	UCH	januslib{0.1-dev} [Janus Compatibility Library] (januslib-0.1.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	jeresources{0.8.1.14} [Just Enough Resources] (JustEnoughResources-1.12-0.8.1.14.jar) 
	UCH	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCH	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UCH	largeveins{@VERSION@} [Large Veins] (LargeVeins-1.12-1.1.0.jar) 
	UCH	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCH	mob_grinding_utils{0.3.1} [mob_grinding_utils] (MobGrindingUtils-0.3.1.jar) 
	UCH	modnametooltip{1.8.1} [Mod Name Tooltip] (modnametooltip_1.12-1.8.1.jar) 
	UCH	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCH	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCH	terraqueous{1.4.0.1} [Terraqueous] (terraqueous-1.12.0-1.4.0.1.jar) 
	UCH	multibeds{1.4.0.1} [Multi-Beds] (multibeds-1.12.0-1.4.0.1.jar) 
	UCH	multistorage{1.4.0.1} [Multi-Storage] (multistorage-1.12.0-1.4.0.1.jar) 
	UCH	musiccraft{3.2.2} [MusicCraft] (MusicCraft-3.2.2.jar) 
	UCH	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1.jar) 
	UCH	mysticalagradditions{1.2.0} [Mystical Agradditions] (mysticalagradditions[1.12]-1.2.0.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCH	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UCH	notenoughwands{1.5.8} [Not Enough Wands] (notenoughwands-1.12-1.5.8.jar) 
	UCH	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UCH	oreexcavation{1.4.100} [OreExcavation] (OreExcavation-1.4.100.jar) 
	UCH	bonecraft{1.12a} [Pam's BoneCraft] (Pam's BoneCraft 1.12a.jar) 
	UCH	clayspawn{1.12a} [Pam's Clay Spawn] (Pam's ClaySpawn 1.12a.jar) 
	UCH	desertcraft{1.11a} [Pam's DesertCraft] (Pam's DesertCraft 1.12a.jar) 
	UCH	getalltheseeds{1.12a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.12a.jar) 
	UCH	simplerecipes{1.12a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.12a.jar) 
	UCH	reborncore{3.2.3.83} [Reborn Core] (RebornCore-1.12-3.2.3.83-universal.jar) 
	UCH	quantumstorage{4.3.4} [QuantumStorage] (QuantumStorage-1.12-4.3.4.jar) 
	UCH	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCH	rainboaks{1.0.4-beta2} [Rainbow Oak Trees] (RainbowOaks-1.12-1.0.4-beta2.jar) 
	UCH	randomthings{4.0.2} [Random Things] (RandomThings-MC1.12-4.0.2.jar) 
	UCH	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCE	redstonearsenal{2.3.0} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.0.4-universal.jar) 
	UCH	refinedrelocation{4.1.4} [Refined Relocation] (RefinedRelocation_1.12-4.1.4.jar) 
	UCH	refinedstorage{1.5.7} [Refined Storage] (refinedstorage-1.5.7.jar) 
	UCH	resourceloader{1.5.2} [Resource Loader] (ResourceLoader-MC1.12-1.5.2.jar) 
	UCH	rftools{6.10} [RFTools] (rftools-1.12-6.10beta3.jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8beta1.jar) 
	UCH	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta1.jar) 
	UCH	roots{0.024} [Roots 2] (roots-2-0.024.jar) 
	UCH	silentlib{2.2.5} [Silent Lib] (SilentLib-1.12-2.2.5b-81.jar) 
	UCH	silentgems{2.4.0} [Silent's Gems] (SilentsGems-1.12-2.4.0-202.jar) 
	UCH	lteleporters{1.11.2-2.1.4} [Simple Teleporters] (simpleteleporters-1.12-2.1.4.jar) 
	UCH	simplytea{1.4} [Simply Tea] (simplytea-1.4.jar) 
	UCH	soulshardstow{1.12-2.7.3-52} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.3-52.jar) 
	UCH	spectritemod{1.2.0} [Spectrite Mod] (spectritemod-1.2.0-1.12.jar) 
	UCH	spiceoflife{1.3.10} [The Spice of Life] (SpiceOfLife-mc1.12-1.3.10.jar) 
	UCH	statues{0.7.1.1} [Statues mod] (statues-0.7.1.1.jar) 
	UCH	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.4.25.jar) 
	UCH	storagedrawers{1.12-5.2.0} [Storage Drawers] (StorageDrawers-1.12-5.2.0.jar) 
	UCH	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCH	techreborn{2.6.6.151} [Tech Reborn] (TechReborn-1.12-2.6.6.151-universal.jar) 
	UCH	tesla{1.0.61} [TESLA] (Tesla-1.12-1.0.61.jar) 
	UCE	thermaldynamics{2.3.0} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.0.4-universal.jar) 
	UCH	thut_wearables{3.0.0} [Thut's Wearables] (thut_wearables-3.0.0.d.jar) 
	UCH	thutcore{5.0.1} [ThutCore] (thutcore-5.0.1.b.jar) 
	UCH	thut_bling{2.0.0} [Thut's Bling] (thut_bling-2.0.0.d.jar) 
	UCH	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCH	torchmaster{1.5.0.31} [TorchMaster] (torchmaster_1.12-1.5.0.31.jar) 
	UCH	totemic{1.12-0.8.10} [Totemic] (Totemic-1.12-0.8.10.jar) 
	UCH	trashslot{8.4.1} [TrashSlot] (TrashSlot_1.12-8.4.1.jar) 
	UCH	underwaterutilities{@VERSION@} [Underwater Utilities] (UnderwaterUtilities-1.12-1.3.1.jar) 
	UCH	uniquecrops{0.1.2} [Unique Crops] (uniquecrops-1.12-0.1.2.jar) 
	UCH	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UCH	vefluids{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [VoltzEngine Fluids module] (VE-FluidHandling-1.12-0.8.0b20170630141359.jar) 
	UCH	waddles{0.5.3} [Waddles] (Waddles-1.12-0.5.3.jar) 
	UCH	wailaharvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.10.jar) 
	UCH	waterpower{@MODVERSION@} [WaterPower] (WaterPower-1.12-0.5.2.jar) 
	UCH	waterstrainer{3.1.1} [Water Strainer] (WaterStrainer-1.12-3.1.1.jar) 
	UCH	wawla{2.5.239} [What Are We Looking At] (Wawla-1.12-2.5.239.jar) 
	UCH	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5.jar) 
	UCH	woodenbucket{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Bucket] (WoodenBuckets-1.12-0.2.0b20170630140308.jar) 
	UCH	wts{1.1.0} [What's That Slot] (WTS-1.1.0.jar) 
	UCH	xnet{1.3.4.3} [XNet] (xnet-1.12-1.3.4.3.jar) 
	UCH	xtones{1.12-1.0.4-7} [Xtones] (Xtones-1.12-1.0.4-7.jar) 
	UCH	yeoldetanks{2.1.0} [Ye Olde Tanks] (YeOldeTanks-1.12-2.1.0.jar) 
	UCH	zombie_steak{1.12-1.2} [Zombie Steak] (zombie_steak-1.12-1.1.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
AstralCore (astralsorcery-1.5.8.jar)
  
AppleCore (AppleCore-mc1.12-2.2.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.5.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  invtweaks.forge.asm.ContainerTransformer
Default Options (DefaultOptions_1.12-9.2.1.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.3-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.1.1.2.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
BlurPlugin (Blur-1.0.3-13.jar)
  com.tterrag.blur.BlurTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.3.83
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.21.1.2397
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by JackyyTV** [comment]
Very weird crash, but I'll let @Shadows-of-Fire to fix that as I am sick.

**Comment by ImAK9** [comment]
Sounds great, i really need this one.

**Comment by JackyyTV** [comment]
I just submitted Exchangers 2.1.1 to CurseForge and waiting for approval. If you really need the jar file now, here's the [direct download link](https://github.com/Jacky1356400/Exchangers/releases/download/1.12-2.1.1/Exchangers-1.12-2.1.1.jar). :)

**Comment by JackyyTV** [comment]
Actually never mind, it's on [CurseForge](https://minecraft.curseforge.com/projects/exchangers/files/2446724) now.

**Comment by ImAK9** [comment]
Great job as always! Thanks!

**Comment by JackyyTV** [comment]
You're welcome :)
